### ISSUE TITLE
Duplicate file names preventing cloning in Windows 10

### ISSUE THREAD

**Issue by Elphikaus** [DSML-book/Programs#1]
Hi,

I went to clone this repository and I received an error with respect to the two files in

`Appendices/Python Primer/output.txt`

The error stated the **path was invalid**.

There are two files with the name `output.txt`.  As a test, I forked this repository and changed the names to `output-01.txt` and `output-02.txt`, re-cloned my forked version and I had no problems forking.  I thought this was a little too small to be considered a pull request.

**Comment by dpkroese** [comment]
Hi Jonathan,
Thanks for letting me know. I just deleted one of the output.txt files. Both are not important.
Best regards,
dirk

**Comment by Elphikaus** [comment]
Even though the names are the same, they are distinct files.
1. `output.txt` that contains `0 10 20 30 40` (this is a transpose) is on page 476 as the bottom output.
2. `output.txt` that contains `Hi there` is on page 477.

I think there still needs to be two distinct files.

Thanks,
Jon

**Comment by Elphikaus** [comment]
Hi,

I just realised my previous message was no needed.  Thanks for the email.
